# PREREQUISITES:
#   - project PROJECT_ID on google cloud
#   - kube cluster in this project with exactly the same name: PROJECT_ID
#   - ConfigMap in the cluster named _APP with the required private
#     environment variables from './config.json' specified
#   - Ingress configuration which proxies port 80 to the serviceName _APP

timeout: 2000s
steps:

- id: main deploy
  name: startupjs/deploy
  args: [batch]
  env:
  # pipe all user defined substitutions
  # you MUST specify each env variable from the `substitutions` section above
  - _APP=$_APP
  - _ZONE=$_ZONE
  - _PATH=$_PATH
  # pipe all default substitutions
  # https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values#using_default_substitutions
  - PROJECT_ID=$PROJECT_ID
  - BUILD_ID=$BUILD_ID
  - COMMIT_SHA=$COMMIT_SHA
  - SHORT_SHA=$SHORT_SHA
  - REPO_NAME=$REPO_NAME
  - BRANCH_NAME=$BRANCH_NAME
  - TAG_NAME=$TAG_NAME
  - REVISION_ID=$REVISION_ID
